import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import MaxWidthWrapper from "./components/MaxWidthWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  flex justify-center py-3 px-6 lg:py-10  dark `}>
        <ToastContainer
          position="top-center"
          autoClose={3500}
          hideProgressBar={false}
          newestOnTop={true}
          closeOnClick={true}
          pauseOnFocusLoss
          pauseOnHover={false}
          theme="dark"
        />
        <MaxWidthWrapper> {children}</MaxWidthWrapper>
      </body>
    </html>
  );
}
